// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package openapi

// Message defines model for Message.
type Message struct {
	Message string `json:"message"`
}

// ScottyChatInput defines model for ScottyChatInput.
type ScottyChatInput struct {
	Message string  `json:"message"`
	Stream  *bool   `json:"stream,omitempty"`
	User    *string `json:"user,omitempty"`
}

// ScottyChatOutput defines model for ScottyChatOutput.
type ScottyChatOutput struct {
	Messages []Message `json:"messages"`
}

// ScottyChatJSONRequestBody defines body for ScottyChat for application/json ContentType.
type ScottyChatJSONRequestBody = ScottyChatInput
